os: linux
dist: xenial
language: python
install:
  - curl -sSL https://raw.githubusercontent.com/python-poetry/poetry/master/get-poetry.py | python
  - python -m pip install poetry-dynamic-versioning
  - source $HOME/.poetry/env
  - echo VIRTUAL_ENV=$VIRTUAL_ENV
  - |
    if [[ $TOXENV != docs ]]; then
      source .travis/install-mopac.sh
    fi
script:
  - poetry build
  - pip install pyberny[test] --pre -f ./dist
  - coverage run -m pytest -v
after_success:
  - coverage xml
  - bash <(curl -s https://codecov.io/bash) -X coveragepy
jobs:
  include:
    - name: Style
      python: 3.7
      install:
        - pip install black flake8 flake8-bugbear flake8-comprehensions flake8-quotes pep8-naming isort pydocstyle
      script:
        - flake8
        - black . --check
        - isort . --check
        - pydocstyle src
    - python: 3.5
    - python: 3.6
    - python: 3.7
    - python: 3.8
    - python: 3.9
    - name: Documentation
      python: 3.7
      script:
        - pip install sphinx sphinxcontrib-katex toml
        - sphinx-build -E docs docs/build
      workspaces:
        create:
          name: ws1
          paths:
            - docs/build
    - stage: deploy
      name: Documentation
      language: minimal
      install: skip
      script: skip
      if: (branch = master) AND (NOT type IN (pull_request)) OR (tag =~ ^\d+\.\d+\.\d+)
      workspaces:
        use: ws1
      deploy:
        provider: pages
        skip_cleanup: true
        token: $GITHUB_TOKEN
        keep_history: true
        local_dir: docs/build
